import Head from "next/head";
import { HeaderLayout } from "@/components/layouts/HeaderLayout/Header.layout";

export default function boxShadowGenerator() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderLayout />
        <p>box shadow</p>
      </main>
    </>
  );
}
