import Head from "next/head";
import { Inter } from "next/font/google";
import { MainSection } from "@/components/sections/MainSection/Main.section";
import { HeaderLayout } from "@/components/layouts/HeaderLayout/Header.layout";

export default function CardGenerator() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderLayout />
        <MainSection />
      </main>
    </>
  );
}
